package dnsmasq

import (
	"fmt"
	"time"
)

var FileHeader string

func init() {
	FileHeader = fmt.Sprintf("# This file is auto generated by faceMasq (https://github.com/jsnfwlr/facemasq/).\n# Any manual changes to it may be wiped when faceMasq next generates this file.\n# File Generated at %s \n\n", time.Now().Format("15:04:05 2006-01-02"))
}
