---
kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node
  commands:
  - cd ui
  - curl -fsSL https://get.pnpm.io/install.sh | sh -
  - pnpm install
  - pnpm build

- name: backend
  image: golang
  commands:
  - cd api
  - go build

trigger:
  event:
  - custom
  - push
  - pull_request

