---
kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node
  commands:
  - cd ui
  - npm install -g pnpm
  - npx browserslist@latest --update-db
  - pnpm install
  - pnpm build

- name: backend
  image: golang
  commands:
  - cd api
  - go build

trigger:
  event:
  - custom
  - push
  - pull_request

