package export

import (
	"fmt"
	"testing"
	"time"
)

func TestGetFileHeader(t *testing.T) {
	baseline := fmt.Sprintf("# This file is auto generated by faceMasq (https://github.com/jsnfwlr/facemasq/).\n# Any manual changes to it may be wiped when faceMasq next generates this file.\n# File Generated at %s\n\n", time.Now().Format("2006-01-02 15:04:05"))
	templated, err := getFileHeaderFromTemplate()
	if err != nil {
		t.Errorf("Error: %v", err)
	}
	if templated != baseline {
		t.Errorf("Expected:\n`%s`\nGot:\n`%s`", baseline, templated)
	}
}
