name: Go

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev, main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          check-latest: true
          stable: true

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
